// Generated by gencpp from file tapir/simRosLoadScene.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSLOADSCENE_H
#define TAPIR_MESSAGE_SIMROSLOADSCENE_H

#include <ros/service_traits.h>


#include <tapir/simRosLoadSceneRequest.h>
#include <tapir/simRosLoadSceneResponse.h>


namespace tapir
{

struct simRosLoadScene
{

typedef simRosLoadSceneRequest Request;
typedef simRosLoadSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosLoadScene
} // namespace tapir


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tapir::simRosLoadScene > {
  static const char* value()
  {
    return "4ce16c0ffb6dc4c97455e3e44d2010aa";
  }

  static const char* value(const ::tapir::simRosLoadScene&) { return value(); }
};

template<>
struct DataType< ::tapir::simRosLoadScene > {
  static const char* value()
  {
    return "tapir/simRosLoadScene";
  }

  static const char* value(const ::tapir::simRosLoadScene&) { return value(); }
};


// service_traits::MD5Sum< ::tapir::simRosLoadSceneRequest> should match 
// service_traits::MD5Sum< ::tapir::simRosLoadScene > 
template<>
struct MD5Sum< ::tapir::simRosLoadSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosLoadScene >::value();
  }
  static const char* value(const ::tapir::simRosLoadSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosLoadSceneRequest> should match 
// service_traits::DataType< ::tapir::simRosLoadScene > 
template<>
struct DataType< ::tapir::simRosLoadSceneRequest>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosLoadScene >::value();
  }
  static const char* value(const ::tapir::simRosLoadSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tapir::simRosLoadSceneResponse> should match 
// service_traits::MD5Sum< ::tapir::simRosLoadScene > 
template<>
struct MD5Sum< ::tapir::simRosLoadSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosLoadScene >::value();
  }
  static const char* value(const ::tapir::simRosLoadSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosLoadSceneResponse> should match 
// service_traits::DataType< ::tapir::simRosLoadScene > 
template<>
struct DataType< ::tapir::simRosLoadSceneResponse>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosLoadScene >::value();
  }
  static const char* value(const ::tapir::simRosLoadSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSLOADSCENE_H
