// Generated by gencpp from file tapir/simRosGetObjectPose.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSGETOBJECTPOSE_H
#define TAPIR_MESSAGE_SIMROSGETOBJECTPOSE_H

#include <ros/service_traits.h>


#include <tapir/simRosGetObjectPoseRequest.h>
#include <tapir/simRosGetObjectPoseResponse.h>


namespace tapir
{

struct simRosGetObjectPose
{

typedef simRosGetObjectPoseRequest Request;
typedef simRosGetObjectPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetObjectPose
} // namespace tapir


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tapir::simRosGetObjectPose > {
  static const char* value()
  {
    return "dcc153fe8e4754d793983e414eb1b664";
  }

  static const char* value(const ::tapir::simRosGetObjectPose&) { return value(); }
};

template<>
struct DataType< ::tapir::simRosGetObjectPose > {
  static const char* value()
  {
    return "tapir/simRosGetObjectPose";
  }

  static const char* value(const ::tapir::simRosGetObjectPose&) { return value(); }
};


// service_traits::MD5Sum< ::tapir::simRosGetObjectPoseRequest> should match 
// service_traits::MD5Sum< ::tapir::simRosGetObjectPose > 
template<>
struct MD5Sum< ::tapir::simRosGetObjectPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosGetObjectPose >::value();
  }
  static const char* value(const ::tapir::simRosGetObjectPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosGetObjectPoseRequest> should match 
// service_traits::DataType< ::tapir::simRosGetObjectPose > 
template<>
struct DataType< ::tapir::simRosGetObjectPoseRequest>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosGetObjectPose >::value();
  }
  static const char* value(const ::tapir::simRosGetObjectPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tapir::simRosGetObjectPoseResponse> should match 
// service_traits::MD5Sum< ::tapir::simRosGetObjectPose > 
template<>
struct MD5Sum< ::tapir::simRosGetObjectPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosGetObjectPose >::value();
  }
  static const char* value(const ::tapir::simRosGetObjectPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosGetObjectPoseResponse> should match 
// service_traits::DataType< ::tapir::simRosGetObjectPose > 
template<>
struct DataType< ::tapir::simRosGetObjectPoseResponse>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosGetObjectPose >::value();
  }
  static const char* value(const ::tapir::simRosGetObjectPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSGETOBJECTPOSE_H
