// Generated by gencpp from file tapir/simRosGetObjectHandleResponse.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSGETOBJECTHANDLERESPONSE_H
#define TAPIR_MESSAGE_SIMROSGETOBJECTHANDLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tapir
{
template <class ContainerAllocator>
struct simRosGetObjectHandleResponse_
{
  typedef simRosGetObjectHandleResponse_<ContainerAllocator> Type;

  simRosGetObjectHandleResponse_()
    : handle(0)  {
    }
  simRosGetObjectHandleResponse_(const ContainerAllocator& _alloc)
    : handle(0)  {
  (void)_alloc;
    }



   typedef int32_t _handle_type;
  _handle_type handle;




  typedef boost::shared_ptr< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simRosGetObjectHandleResponse_

typedef ::tapir::simRosGetObjectHandleResponse_<std::allocator<void> > simRosGetObjectHandleResponse;

typedef boost::shared_ptr< ::tapir::simRosGetObjectHandleResponse > simRosGetObjectHandleResponsePtr;
typedef boost::shared_ptr< ::tapir::simRosGetObjectHandleResponse const> simRosGetObjectHandleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tapir

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'tapir': ['/home/crazy/Desktop/catkin_ws/src/tapir/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92535b678299d2bdda959704e78c275e";
  }

  static const char* value(const ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92535b678299d2bdULL;
  static const uint64_t static_value2 = 0xda959704e78c275eULL;
};

template<class ContainerAllocator>
struct DataType< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tapir/simRosGetObjectHandleResponse";
  }

  static const char* value(const ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 handle\n\
\n\
";
  }

  static const char* value(const ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.handle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosGetObjectHandleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tapir::simRosGetObjectHandleResponse_<ContainerAllocator>& v)
  {
    s << indent << "handle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.handle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSGETOBJECTHANDLERESPONSE_H
