// Generated by gencpp from file tapir/simRosStartSimulationResponse.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSSTARTSIMULATIONRESPONSE_H
#define TAPIR_MESSAGE_SIMROSSTARTSIMULATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tapir
{
template <class ContainerAllocator>
struct simRosStartSimulationResponse_
{
  typedef simRosStartSimulationResponse_<ContainerAllocator> Type;

  simRosStartSimulationResponse_()
    : result(0)  {
    }
  simRosStartSimulationResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simRosStartSimulationResponse_

typedef ::tapir::simRosStartSimulationResponse_<std::allocator<void> > simRosStartSimulationResponse;

typedef boost::shared_ptr< ::tapir::simRosStartSimulationResponse > simRosStartSimulationResponsePtr;
typedef boost::shared_ptr< ::tapir::simRosStartSimulationResponse const> simRosStartSimulationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tapir::simRosStartSimulationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tapir

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'tapir': ['/home/crazy/Desktop/catkin_ws/src/tapir/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::tapir::simRosStartSimulationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tapir/simRosStartSimulationResponse";
  }

  static const char* value(const ::tapir::simRosStartSimulationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n\
\n\
";
  }

  static const char* value(const ::tapir::simRosStartSimulationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosStartSimulationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tapir::simRosStartSimulationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tapir::simRosStartSimulationResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSSTARTSIMULATIONRESPONSE_H
