// Generated by gencpp from file tapir/simRosSetObjectPosition.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSSETOBJECTPOSITION_H
#define TAPIR_MESSAGE_SIMROSSETOBJECTPOSITION_H

#include <ros/service_traits.h>


#include <tapir/simRosSetObjectPositionRequest.h>
#include <tapir/simRosSetObjectPositionResponse.h>


namespace tapir
{

struct simRosSetObjectPosition
{

typedef simRosSetObjectPositionRequest Request;
typedef simRosSetObjectPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosSetObjectPosition
} // namespace tapir


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tapir::simRosSetObjectPosition > {
  static const char* value()
  {
    return "6f49de0c0a94265fc772061f892cd142";
  }

  static const char* value(const ::tapir::simRosSetObjectPosition&) { return value(); }
};

template<>
struct DataType< ::tapir::simRosSetObjectPosition > {
  static const char* value()
  {
    return "tapir/simRosSetObjectPosition";
  }

  static const char* value(const ::tapir::simRosSetObjectPosition&) { return value(); }
};


// service_traits::MD5Sum< ::tapir::simRosSetObjectPositionRequest> should match 
// service_traits::MD5Sum< ::tapir::simRosSetObjectPosition > 
template<>
struct MD5Sum< ::tapir::simRosSetObjectPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosSetObjectPosition >::value();
  }
  static const char* value(const ::tapir::simRosSetObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosSetObjectPositionRequest> should match 
// service_traits::DataType< ::tapir::simRosSetObjectPosition > 
template<>
struct DataType< ::tapir::simRosSetObjectPositionRequest>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosSetObjectPosition >::value();
  }
  static const char* value(const ::tapir::simRosSetObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tapir::simRosSetObjectPositionResponse> should match 
// service_traits::MD5Sum< ::tapir::simRosSetObjectPosition > 
template<>
struct MD5Sum< ::tapir::simRosSetObjectPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosSetObjectPosition >::value();
  }
  static const char* value(const ::tapir::simRosSetObjectPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosSetObjectPositionResponse> should match 
// service_traits::DataType< ::tapir::simRosSetObjectPosition > 
template<>
struct DataType< ::tapir::simRosSetObjectPositionResponse>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosSetObjectPosition >::value();
  }
  static const char* value(const ::tapir::simRosSetObjectPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSSETOBJECTPOSITION_H
