// Generated by gencpp from file tapir/simRosStopSimulation.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSSTOPSIMULATION_H
#define TAPIR_MESSAGE_SIMROSSTOPSIMULATION_H

#include <ros/service_traits.h>


#include <tapir/simRosStopSimulationRequest.h>
#include <tapir/simRosStopSimulationResponse.h>


namespace tapir
{

struct simRosStopSimulation
{

typedef simRosStopSimulationRequest Request;
typedef simRosStopSimulationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosStopSimulation
} // namespace tapir


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tapir::simRosStopSimulation > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::tapir::simRosStopSimulation&) { return value(); }
};

template<>
struct DataType< ::tapir::simRosStopSimulation > {
  static const char* value()
  {
    return "tapir/simRosStopSimulation";
  }

  static const char* value(const ::tapir::simRosStopSimulation&) { return value(); }
};


// service_traits::MD5Sum< ::tapir::simRosStopSimulationRequest> should match 
// service_traits::MD5Sum< ::tapir::simRosStopSimulation > 
template<>
struct MD5Sum< ::tapir::simRosStopSimulationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosStopSimulation >::value();
  }
  static const char* value(const ::tapir::simRosStopSimulationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosStopSimulationRequest> should match 
// service_traits::DataType< ::tapir::simRosStopSimulation > 
template<>
struct DataType< ::tapir::simRosStopSimulationRequest>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosStopSimulation >::value();
  }
  static const char* value(const ::tapir::simRosStopSimulationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tapir::simRosStopSimulationResponse> should match 
// service_traits::MD5Sum< ::tapir::simRosStopSimulation > 
template<>
struct MD5Sum< ::tapir::simRosStopSimulationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosStopSimulation >::value();
  }
  static const char* value(const ::tapir::simRosStopSimulationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosStopSimulationResponse> should match 
// service_traits::DataType< ::tapir::simRosStopSimulation > 
template<>
struct DataType< ::tapir::simRosStopSimulationResponse>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosStopSimulation >::value();
  }
  static const char* value(const ::tapir::simRosStopSimulationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSSTOPSIMULATION_H
