// Generated by gencpp from file tapir/simRosGetObjectHandle.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSGETOBJECTHANDLE_H
#define TAPIR_MESSAGE_SIMROSGETOBJECTHANDLE_H

#include <ros/service_traits.h>


#include <tapir/simRosGetObjectHandleRequest.h>
#include <tapir/simRosGetObjectHandleResponse.h>


namespace tapir
{

struct simRosGetObjectHandle
{

typedef simRosGetObjectHandleRequest Request;
typedef simRosGetObjectHandleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetObjectHandle
} // namespace tapir


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tapir::simRosGetObjectHandle > {
  static const char* value()
  {
    return "5ede8bf5f32716bfd1ea7a68b46333e8";
  }

  static const char* value(const ::tapir::simRosGetObjectHandle&) { return value(); }
};

template<>
struct DataType< ::tapir::simRosGetObjectHandle > {
  static const char* value()
  {
    return "tapir/simRosGetObjectHandle";
  }

  static const char* value(const ::tapir::simRosGetObjectHandle&) { return value(); }
};


// service_traits::MD5Sum< ::tapir::simRosGetObjectHandleRequest> should match 
// service_traits::MD5Sum< ::tapir::simRosGetObjectHandle > 
template<>
struct MD5Sum< ::tapir::simRosGetObjectHandleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosGetObjectHandle >::value();
  }
  static const char* value(const ::tapir::simRosGetObjectHandleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosGetObjectHandleRequest> should match 
// service_traits::DataType< ::tapir::simRosGetObjectHandle > 
template<>
struct DataType< ::tapir::simRosGetObjectHandleRequest>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosGetObjectHandle >::value();
  }
  static const char* value(const ::tapir::simRosGetObjectHandleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tapir::simRosGetObjectHandleResponse> should match 
// service_traits::MD5Sum< ::tapir::simRosGetObjectHandle > 
template<>
struct MD5Sum< ::tapir::simRosGetObjectHandleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosGetObjectHandle >::value();
  }
  static const char* value(const ::tapir::simRosGetObjectHandleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosGetObjectHandleResponse> should match 
// service_traits::DataType< ::tapir::simRosGetObjectHandle > 
template<>
struct DataType< ::tapir::simRosGetObjectHandleResponse>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosGetObjectHandle >::value();
  }
  static const char* value(const ::tapir::simRosGetObjectHandleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSGETOBJECTHANDLE_H
