// Generated by gencpp from file tapir/simRosCopyPasteObjects.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSCOPYPASTEOBJECTS_H
#define TAPIR_MESSAGE_SIMROSCOPYPASTEOBJECTS_H

#include <ros/service_traits.h>


#include <tapir/simRosCopyPasteObjectsRequest.h>
#include <tapir/simRosCopyPasteObjectsResponse.h>


namespace tapir
{

struct simRosCopyPasteObjects
{

typedef simRosCopyPasteObjectsRequest Request;
typedef simRosCopyPasteObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosCopyPasteObjects
} // namespace tapir


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tapir::simRosCopyPasteObjects > {
  static const char* value()
  {
    return "6c736eb743dc1dca49bfc35e3f009776";
  }

  static const char* value(const ::tapir::simRosCopyPasteObjects&) { return value(); }
};

template<>
struct DataType< ::tapir::simRosCopyPasteObjects > {
  static const char* value()
  {
    return "tapir/simRosCopyPasteObjects";
  }

  static const char* value(const ::tapir::simRosCopyPasteObjects&) { return value(); }
};


// service_traits::MD5Sum< ::tapir::simRosCopyPasteObjectsRequest> should match 
// service_traits::MD5Sum< ::tapir::simRosCopyPasteObjects > 
template<>
struct MD5Sum< ::tapir::simRosCopyPasteObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosCopyPasteObjects >::value();
  }
  static const char* value(const ::tapir::simRosCopyPasteObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosCopyPasteObjectsRequest> should match 
// service_traits::DataType< ::tapir::simRosCopyPasteObjects > 
template<>
struct DataType< ::tapir::simRosCopyPasteObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosCopyPasteObjects >::value();
  }
  static const char* value(const ::tapir::simRosCopyPasteObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tapir::simRosCopyPasteObjectsResponse> should match 
// service_traits::MD5Sum< ::tapir::simRosCopyPasteObjects > 
template<>
struct MD5Sum< ::tapir::simRosCopyPasteObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosCopyPasteObjects >::value();
  }
  static const char* value(const ::tapir::simRosCopyPasteObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosCopyPasteObjectsResponse> should match 
// service_traits::DataType< ::tapir::simRosCopyPasteObjects > 
template<>
struct DataType< ::tapir::simRosCopyPasteObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosCopyPasteObjects >::value();
  }
  static const char* value(const ::tapir::simRosCopyPasteObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSCOPYPASTEOBJECTS_H
