// Generated by gencpp from file tapir/simRosStopSimulationRequest.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSSTOPSIMULATIONREQUEST_H
#define TAPIR_MESSAGE_SIMROSSTOPSIMULATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tapir
{
template <class ContainerAllocator>
struct simRosStopSimulationRequest_
{
  typedef simRosStopSimulationRequest_<ContainerAllocator> Type;

  simRosStopSimulationRequest_()
    {
    }
  simRosStopSimulationRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosStopSimulationRequest_

typedef ::tapir::simRosStopSimulationRequest_<std::allocator<void> > simRosStopSimulationRequest;

typedef boost::shared_ptr< ::tapir::simRosStopSimulationRequest > simRosStopSimulationRequestPtr;
typedef boost::shared_ptr< ::tapir::simRosStopSimulationRequest const> simRosStopSimulationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tapir::simRosStopSimulationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tapir

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'tapir': ['/home/crazy/Desktop/catkin_ws/src/tapir/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::tapir::simRosStopSimulationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tapir/simRosStopSimulationRequest";
  }

  static const char* value(const ::tapir::simRosStopSimulationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::tapir::simRosStopSimulationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosStopSimulationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tapir::simRosStopSimulationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::tapir::simRosStopSimulationRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSSTOPSIMULATIONREQUEST_H
