// Generated by gencpp from file tapir/simRosStartSimulation.msg
// DO NOT EDIT!


#ifndef TAPIR_MESSAGE_SIMROSSTARTSIMULATION_H
#define TAPIR_MESSAGE_SIMROSSTARTSIMULATION_H

#include <ros/service_traits.h>


#include <tapir/simRosStartSimulationRequest.h>
#include <tapir/simRosStartSimulationResponse.h>


namespace tapir
{

struct simRosStartSimulation
{

typedef simRosStartSimulationRequest Request;
typedef simRosStartSimulationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosStartSimulation
} // namespace tapir


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tapir::simRosStartSimulation > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::tapir::simRosStartSimulation&) { return value(); }
};

template<>
struct DataType< ::tapir::simRosStartSimulation > {
  static const char* value()
  {
    return "tapir/simRosStartSimulation";
  }

  static const char* value(const ::tapir::simRosStartSimulation&) { return value(); }
};


// service_traits::MD5Sum< ::tapir::simRosStartSimulationRequest> should match 
// service_traits::MD5Sum< ::tapir::simRosStartSimulation > 
template<>
struct MD5Sum< ::tapir::simRosStartSimulationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosStartSimulation >::value();
  }
  static const char* value(const ::tapir::simRosStartSimulationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosStartSimulationRequest> should match 
// service_traits::DataType< ::tapir::simRosStartSimulation > 
template<>
struct DataType< ::tapir::simRosStartSimulationRequest>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosStartSimulation >::value();
  }
  static const char* value(const ::tapir::simRosStartSimulationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tapir::simRosStartSimulationResponse> should match 
// service_traits::MD5Sum< ::tapir::simRosStartSimulation > 
template<>
struct MD5Sum< ::tapir::simRosStartSimulationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tapir::simRosStartSimulation >::value();
  }
  static const char* value(const ::tapir::simRosStartSimulationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tapir::simRosStartSimulationResponse> should match 
// service_traits::DataType< ::tapir::simRosStartSimulation > 
template<>
struct DataType< ::tapir::simRosStartSimulationResponse>
{
  static const char* value()
  {
    return DataType< ::tapir::simRosStartSimulation >::value();
  }
  static const char* value(const ::tapir::simRosStartSimulationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAPIR_MESSAGE_SIMROSSTARTSIMULATION_H
